---
prod: 
  app_function: process_entries.main
  apigateway_enabled: false
  aws_region: us-east-1
  profile_name: gtma
  project_name: backend
  runtime: python3.10
  s3_bucket: zappa-okc-chmp-backend-prod
  events: 
    - function: process_entries.main
      event_source: 
          arn: arn:aws:sqs:us-east-1:851725437474:processing
          batch_size: 1
          enabled: true
  dead_letter_arn: arn:aws:sqs:us-east-1:851725437474:failed_registrations
  remote_env: s3://tkd-reg-config20241122160149102200000006/backend.json
  parameter_depth: 1
  memory_size: 512
  use_precompiled_packages: true
  slim_handler: true
