---
dev: 
  app_function: process_entries.main
  apigateway_enabled: false
  aws_region: us-east-1
  profile_name: personal
  project_name: okgp_backend
  runtime: python3.11
  s3_bucket: zappa-okgp-backend-dev
  layers: 
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:4
  events: 
    - function: process_entries.main
      event_source: 
          arn: arn:aws:sqs:us-east-1:799879571353:okgp_processing_dev
          batch_size: 1
          enabled: true
  dead_letter_arn: arn:aws:sqs:us-east-1:799879571353:okgp_failed_regs_dev
  remote_env: s3://okgp-reg-config/backend.json
  parameter_depth: 1
  memory_size: 512
  use_precompiled_packages: true
  slim_handler: true
prod:
  app_function: process_entries.main
  apigateway_enabled: false
  aws_region: us-east-1
  profile_name: gdtkd
  project_name: backend
  runtime: python3.11
  s3_bucket: zappa-okgp25-backend-prod
  layers:
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:4
  events:
    - function: process_entries.main
      event_source:
        arn: arn:aws:sqs:us-east-1:058264481846:processing
        batch_size: 1
        enabled: true
  dead_letter_arn: arn:aws:sqs:us-east-1:058264481846:failed_registrations
  remote_env: s3://okgp25-reg-config/backend.json
  parameter_depth: 1
  memory_size: 512
  use_precompiled_packages: true