---
prod:
  app_function: process_entries.main
  apigateway_enabled: false
  aws_region: us-east-2
  profile_name: personal
  project_name: backend
  runtime: python3.11
  s3_bucket: zappa-okgp24-backend-prod
  layers:
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:4
  events:
    - function: process_entries.main
      event_source:
        arn: arn:aws:sqs:us-east-2:799879571353:processing
        batch_size: 1
        enabled: true
  dead_letter_arn: arn:aws:sqs:us-east-2:799879571353:failed_registrations
  remote_env: s3://okgp24-reg-config/backend.json
  parameter_depth: 1
  memory_size: 512
  use_precompiled_packages: true