name: 'Backend Tests'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  backend:
    name: 'Backend Tests'
    runs-on: ubuntu-latest
    environment: Test

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        role-session-name: BackendTest
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # Install a specific version of uv.
        version: "0.4.26"

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run Tests
      env:
        ADMIN_EMAIL: "${{ vars.ADMIN_EMAIL }}"
        BADGE_BUCKET: "${{ vars.BADGE_BUCKET }}"
        BADGE_GFOLDER: "${{ vars.BADGE_GFOLDER }}"
        COMPETITION_NAME: "${{ vars.COMPETITION_NAME }}"
        COMPETITION_YEAR: "${{ vars.COMPETITION_YEAR }}"
        CONFIG_BUCKET: "${{ vars.CONFIG_BUCKET }}"
        CONTACT_EMAIL: "${{ vars.CONTACT_EMAIL }}"
        DB_TABLE: "${{ vars.DB_TABLE }}"
        EMAIL_PASSWD: "${{ secrets.EMAIL_PASSWORD }}"
        EMAIL_PORT: "${{ vars.EMAIL_PORT }}"
        EMAIL_SERVER: "${{ vars.EMAIL_SERVER }}"
        FROM_EMAIL: "${{ vars.FROM_EMAIL }}"
        PROFILE_PIC_BUCKET: "${{ vars.PROFILE_PIC_BUCKET }}"
        SQS_QUEUE_URL: "${{ vars.SQS_QUEUE_URL }}"
        STRIPE_API_KEY: "${{ secrets.STRIPE_API_KEY }}"
        STRIPE_TEST_SESSION: "${{ secrets.STRIPE_TEST_SESSION }}"
      run: uv run pytest -qrA --tb=no >> $GITHUB_STEP_SUMMARY

  security:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@main
      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          api-key: "${{ secrets.SAFETY_API_KEY }}"
