name: 'Backend Tests'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  backend:
    name: 'Backend Tests'
    runs-on: ubuntu-latest
    environment: Test

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::799879571353:role/GitHub_Actions
        role-session-name: BackendTest
        aws-region: us-east-1

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt

    - id: execute-process_entries
      name: Run 'process_entries.py'
      env:
        BADGE_BUCKET: "${{ env.BADGE_BUCKET }}"
        BADGE_GFOLDER: "${{ env.BADGE_GFOLDER }}"
        COMPETITION_NAME: "${{ env.COMPETITION_NAME }}"
        COMPETITION_YEAR: "${{ env.COMPETITION_YEAR }}"
        CONFIG_BUCKET: "${{ env.CONFIG_BUCKET }}"
        CONTACT_EMAIL: "${{ env.CONTACT_EMAIL }}"
        DB_TABLE: "${{ env.DB_TABLE }}"
        EMAIL_PASSWD: "${{ secrets.EMAIL_PASSWORD }}"
        EMAIL_PORT: "${{ env.EMAIL_PORT }}"
        EMAIL_SERVER: "${{ env.EMAIL_SERVER }}"
        FROM_EMAIL: "${{ env.FROM_EMAIL }}"
        PROFILE_PIC_BUCKET: "${{ env.PROFILE_PIC_BUCKET }}"
        SQS_QUEUE_URL: "${{ env.SQS_QUEUE_URL }}"
        STRIPE_API_KEY: "${{ secrets.STRIPE_API_KEY }}"
      run: |
        echo "Table: $DB_TABLE"
        python process_entries.py
    - uses: nick-fields/assert-action@v2
      with:
        expected: |
          Processing 1 entries
            Processing Test User
          Entry added for Test User as a competitor
          Mail Sent!
            Test User Processed Successfully
        actual: ${{ steps.execute-process_entries.outputs.value }}

    - id: execute-cleanup
      name: Run 'cleanup.py'
      env:
        DB_TABLE: "${{ env.DB_TABLE }}"
      run: |
        python tests/cleanup_test_entry.py
    - uses: nick-fields/assert-action@v2
      with:
        expected: Test User successfully deleted
        actual: ${{ steps.execute-cleanup.outputs.value }}